[danchu]
title = "단추tv"
url = "https://danchu.tv/ticket_open"
entrySelector = "ul.xe-list-webzine-board-list li.xe-list-webzine-board-list-item"
titleSelector = "h2.xe-list-webzine-board-list-item__title"
linkSelector = "a.xe-list-webzine-board-list-item__text-link"
contentSelector = "span.xe-list-webzine-board-ticket-open"
imageSelector = "div.xe-list-webzine-board-list-item__img"
waitUntil = "networkidle"