[danchu]
title = "단추tv"
url = "https://danchu.tv/ticket_open"
entrySelector = "ul.xe-list-webzine-board-list li.xe-list-webzine-board-list-item"
titleSelector = "h2.xe-list-webzine-board-list-item__title"
linkSelector = "a.xe-list-webzine-board-list-item__text-link"
contentSelector = "span.xe-list-webzine-board-ticket-open"
imageSelector = "div.xe-list-webzine-board-list-item__img"
waitUntil = "networkidle"

[danchu_top]
title = "단추tv"
url = "https://danchu.tv/ticket_open"
entrySelector = "div[class='swiper-wrapper xf-main-slide'] a[class^='swiper-slide main-slide-link']"
titleSelector = "h3.xf-slide-title"
linkSelector = "a[class^='swiper-slide main-slide-link']"
contentSelector = "p.xf-slide-date"
imageSelector = "div.main-slide-img"
waitUntil = "networkidle"

[artistscard]
title = "Artists'Card"
url = "https://artistscard.com/ko/ticket"
entrySelector = "div[class='sc-1cyq3hq-3 jzKJLm'] div[class='sc-1e3tjec-0 gbEYpG']"
titleSelector = "div[class='sc-1e3tjec-5 sc-1e3tjec-7 bcogIH jxILRF']"
linkSelector = "a"
contentSelector = "div[class='sc-1e3tjec-5 sc-1e3tjec-8 bcogIH fEyMUm']"
waitUntil = "networkidle"

[bbangyatv]
title = "빵야 TV"
url = "https://www.bbangyatv.com/main"
entrySelector = "div[class='d-flex flex-wrap v-card v-card--flat v-sheet theme--light'] div[class='schedule-card v-card v-card--flat v-sheet theme--light']"
titleSelector = "h4[class='subtitle-1 twoLineEllipsis font-weight-medium']"
linkSelector = "a"
contentSelector = "div[class='ml-2']"
imageSelector = "div[class='v-image__image v-image__image--cover']"
waitUntil = "networkidle"
